name: Vectormath

on:
  push:
  pull_request:

jobs:
  linux:
    strategy:
      matrix:
        compiler: [g++, clang++]
    runs-on: ubuntu-latest
    env:
      CXX: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: >
          cmake -S . -B build
          -DMOVE_VECTORMATH_BUILD_STANDALONE_TESTS=ON
          -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel 2
      - name: Test
        run: ctest --test-dir build --output-on-failure

  platforms:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: >
          cmake -S . -B build
          -DMOVE_VECTORMATH_BUILD_STANDALONE_TESTS=ON
          -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release --parallel 2
      - name: Test
        run: ctest --test-dir build --output-on-failure -C Release
